export function exportAmortizationToCSV(
    data: {
      calendarMonth: string;
      calendarYear: number;
      opening: number;
      principal: number;
      interest: number;
      payment: number;
      balance: number;
      totalInterestPaid: number;
    }[],
    fileName = "emi_schedule.csv"
  ) {
    if (!data || !data.length) return;
  
    const headers = [
      "Month",
      "Opening Balance (₹)",
      "Principal (₹)",
      "Interest (₹)",
      "EMI Payment (₹)",
      "Closing Balance (₹)",
      "Total Interest Paid (₹)",
    ];
  
    const rows = data.map((row) => [
      `${row.calendarMonth} ${row.calendarYear}`,
      Math.round(row.opening),
      Math.round(row.principal),
      Math.round(row.interest),
      Math.round(row.payment),
      Math.round(row.balance),
      Math.round(row.totalInterestPaid),
    ]);
  
    const csvContent =
      [headers, ...rows]
        .map((row) => row.join(","))
        .join("\n");
  
    const watermarkRow = "\nGenerated by EMIPro.in - Smart Financial Tools 💼";
  
    const blob = new Blob([csvContent + watermarkRow], {
      type: "text/csv;charset=utf-8;",
    });
  
    const url = URL.createObjectURL(blob);
  
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", fileName);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
  